import type { ProjectDetail } from "@/lib/project-types";

export const staticProjectsBySlug: Record<string, ProjectDetail> =
{
  "fafen-river-irrigation": {
    title: "Fafen River Irrigation Scheme",
    category: "Irrigation",
    client: "Somali Regional State Bureau of Agriculture",
    location: "Jigjiga Zone, Somali Region, Ethiopia",
    projectSize: "1,500 HA",
    completionDate: "2022",
    status: "Completed",
    image: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=1200&q=85",
    shortDescription: "Feasibility study, detailed design, and construction supervision of a 1,500 HA surface irrigation scheme fed by Fafen River in the Jigjiga Zone.",
    fullDescription: [
      "The Fafen River Irrigation Scheme represents one of HAGEC's flagship projects and the largest completed irrigation development in the Somali Region. Commissioned by the Somali Regional State Bureau of Agriculture, the project covers a net irrigable area of 1,500 hectares across the Fafen River basin.",
      "HAGEC was responsible for the full project cycle: inception and scoping, topographic survey, hydrological analysis, geotechnical investigation, hydraulic design, construction supervision, and preparation of operation and maintenance manuals.",
      "The scheme utilizes a gravity-fed diversion weir on the Fafen River, feeding a primary canal network of 18 km and secondary/tertiary distribution canals totalling 64 km. The hydraulic design accommodates a peak irrigation demand of 2.8 m³/s, with an efficiency-optimized canal cross-section profile developed using HEC-RAS modelling.",
    ],
    keyResults: [
      "1,500 hectares of previously rain-fed land brought under perennial irrigation",
      "Direct benefit to over 2,400 smallholder farming households",
      "Estimated annual agricultural output increase of ETB 185 million",
      "17 km of primary canal constructed to design specifications",
      "5 major hydraulic structures designed and built (headworks, regulators, off-takes)",
      "100% project completion within budget and on schedule",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&q=80",
      "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80",
      "https://images.unsplash.com/photo-1531966817680-4a1dbf9fbd72?w=800&q=80",
      "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800&q=80",
    ],
  },
  "wabe-shebelle-solar-pump": {
    title: "Wabe Shebelle Solar-Pump System",
    category: "Solar-Pump",
    client: "FAO Ethiopia",
    location: "Gode Zone, Somali Region, Ethiopia",
    projectSize: "—",
    completionDate: "2021",
    status: "Completed",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=85",
    shortDescription: "Design and installation supervision of a 45 kW solar-pump system providing irrigation water to 200 smallholder farmers.",
    fullDescription: [
      "The Wabe Shebelle Solar-Pump System project was implemented under FAO Ethiopia's livelihoods resilience programme for conflict-affected communities in Gode Zone. HAGEC designed a solar-powered pumping system capable of lifting water from the Wabe Shebelle River to serve 200 smallholder farmers.",
      "The system comprises a 45 kW photovoltaic array, two submersible pumps, a control house, storage reservoir, and a gravity-distribution network to the field plots. HAGEC conducted solar resource analysis, hydraulic design, pump sizing, PV system design, and bill of quantities, followed by full construction supervision.",
    ],
    keyResults: [
      "45 kW solar PV system installed and operational",
      "200 farming households provided with reliable irrigation water",
      "Zero fossil-fuel dependency — completely off-grid system",
      "360 m³/hour pumping capacity at design head",
      "System designed for 25-year operational life",
      "Full O&M training delivered to community management committee",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
  },
  "waberi-canal-rehabilitation": {
    title: "Waberi Canal Rehabilitation",
    category: "Irrigation",
    client: "World Bank / Somali Regional State",
    location: "Gode Zone, Somali Region, Ethiopia",
    projectSize: "800 HA",
    completionDate: "2023",
    status: "Completed",
    image: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&q=85",
    shortDescription: "Rehabilitation of primary and secondary canals of the existing 800 HA Waberi irrigation scheme, including hydraulic modelling and design.",
    fullDescription: [
      "The Waberi Canal Rehabilitation project was funded under a World Bank-supported irrigation development programme. HAGEC was engaged to rehabilitate the primary (12 km) and secondary canal network (38 km) of the existing 800 HA Waberi irrigation scheme which had fallen into disrepair.",
      "HAGEC conducted a full condition survey, hydraulic re-modelling using HEC-RAS and EPANET, and prepared a detailed rehabilitation design incorporating concrete lining of critical reaches, relief structure upgrades, and new water measurement structures.",
    ],
    keyResults: [
      "12 km primary canal and 38 km secondary canals rehabilitated",
      "Conveyance efficiency improved from 48% to 78%",
      "800 HA of agricultural land restored to full production",
      "1,100 farming households reinstated",
      "Water measurement structures installed at 24 locations",
      "Detailed O&M manual prepared for local water users association",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80",
      "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&q=80",
    ],
  },
  "jigjiga-water-supply-eia": {
    title: "Jigjiga Water Supply EIA",
    category: "EIA",
    client: "Somali Urban Water Supply Authority",
    location: "Jigjiga, Somali Region, Ethiopia",
    projectSize: "—",
    completionDate: "2023",
    status: "Completed",
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&q=85",
    shortDescription: "Full Environmental Impact Assessment and Environmental and Social Management Plan for the Jigjiga municipal water supply expansion project.",
    fullDescription: [
      "HAGEC conducted a comprehensive Environmental Impact Assessment and Environmental and Social Management Plan for the expansion of the Jigjiga municipal water supply system, funded by the African Development Bank. The project scope included a new water intake on the Fafen River, a water treatment plant, and 45 km of transmission and distribution mains.",
    ],
    keyResults: [
      "Full ESIA report compliant with Ethiopian EPA and AfDB standards",
      "Baseline biodiversity and ecosystem survey completed",
      "ESMP with 48 mitigation measures developed",
      "Stakeholder consultation with 12 communities conducted",
      "Resettlement screening completed for pipeline corridor",
      "Environmental compliance monitoring programme designed",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&q=80",
    ],
  },
  "somali-region-land-use-mapping": {
    title: "Somali Region Land Use Mapping",
    category: "GIS & Surveying",
    client: "UNDP Ethiopia",
    location: "Somali Region (Multi-zone)",
    projectSize: "—",
    completionDate: "2022",
    status: "Completed",
    image: "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=1200&q=85",
    shortDescription: "Satellite image-based land use and land cover mapping of five zones of the Somali Region using GIS and remote sensing analysis.",
    fullDescription: [
      "Under a UNDP-funded natural resource management programme, HAGEC produced comprehensive land use and land cover (LULC) maps for five administrative zones of Somali Region using multi-temporal Sentinel-2 satellite imagery and advanced GIS classification techniques.",
    ],
    keyResults: [
      "Land use maps produced for 5 zones at 1:50,000 scale",
      "10 land cover classes mapped with >85% overall accuracy",
      "Change detection analysis for 2010–2022 period",
      "Hotspot areas of land degradation identified and mapped",
      "GIS database and web map portal delivered to UNDP",
      "Remote sensing methodology manual produced for government staff",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800&q=80",
    ],
  },
  "erer-valley-geotechnical": {
    title: "Erer Valley Geotechnical Study",
    category: "Geotechnical",
    client: "Ministry of Water & Energy, Ethiopia",
    location: "Erer Valley, Somali Region",
    projectSize: "—",
    completionDate: "2021",
    status: "Completed",
    image: "https://images.unsplash.com/photo-1531966817680-4a1dbf9fbd72?w=1200&q=85",
    shortDescription: "Geotechnical investigation for a proposed earth dam, including borehole drilling, laboratory testing, and foundation engineering report.",
    fullDescription: [
      "HAGEC conducted a full programme of geotechnical investigation for a proposed earth-fill dam in the Erer Valley. The investigation programme included geological mapping, test pits, rotary boreholes to 25 m depth, standard penetration testing, laboratory soil and rock testing, and seismic refraction surveys.",
    ],
    keyResults: [
      "8 boreholes drilled and logged to 25 m depth",
      "24 test pits excavated and sampled",
      "Full suite of laboratory tests performed on 142 samples",
      "Seismic refraction survey completed along 3 profiles",
      "Foundation engineering recommendations provided for dam axis",
      "Construction materials investigation report completed",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1531966817680-4a1dbf9fbd72?w=800&q=80",
    ],
  },
  "fafen-basin-hydrology": {
    title: "Fafen Basin Hydrological Study",
    category: "Hydrology",
    client: "FAO Ethiopia / Somali Regional State",
    location: "Fafen River Basin, Somali Region",
    projectSize: "—",
    completionDate: "2024",
    status: "Ongoing",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=85",
    shortDescription: "Comprehensive hydrological and water resources study of the Fafen River Basin including flood analysis, water balance, and flow rating curves.",
    fullDescription: [
      "This ongoing study commissioned by FAO Ethiopia provides a comprehensive hydrological and water resources assessment of the entire Fafen River Basin — the primary water source for the Jigjiga Zone. HAGEC is conducting multi-year streamflow monitoring, rainfall analysis, and water balance modelling to inform long-term irrigation development planning.",
    ],
    keyResults: [
      "18 stream gauging stations installed and operational",
      "25-year flood frequency analysis completed",
      "Water balance model calibrated using 30 years of data",
      "Groundwater recharge estimation completed",
      "Stage-discharge rating curves established for 8 main gauging sites",
      "Hydrogeological map of the basin produced",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
  },
  "northern-somali-irrigation-feasibility": {
    title: "Northern Somali Irrigation Feasibility",
    category: "Feasibility Study",
    client: "African Development Bank",
    location: "Shinile Zone, Somali Region",
    projectSize: "2,500 HA",
    completionDate: "2025",
    status: "Ongoing",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&q=85",
    shortDescription: "Pre-feasibility and feasibility study for a new 2,500 HA irrigation scheme in Shinile Zone, including topographic survey and hydrological assessment.",
    fullDescription: [
      "HAGEC is currently conducting a pre-feasibility and feasibility study for a proposed 2,500 HA irrigation development in Shinile Zone, co-financed by the African Development Bank and the Somali Regional State. The study encompasses topographic survey of 4,500 HA using drone photogrammetry, hydrological analysis, geotechnical investigation, environmental scoping, and socio-economic assessment.",
    ],
    keyResults: [
      "Drone photogrammetry survey of 4,500 HA completed",
      "4 candidate irrigation command areas identified and ranked",
      "Hydrological analysis for 3 potential diversion points",
      "Socio-economic survey of 800 farming households conducted",
      "Preliminary irrigation layout design prepared",
      "Feasibility report submission expected Q4 2025",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
    ],
  },
};
