import type { ProjectListItem } from "@/lib/project-types";

export const STATIC_PROJECTS_LIST: ProjectListItem[] = [
  {
    id: 1,
    title: "Fafen River Irrigation Scheme",
    slug: "fafen-river-irrigation",
    category: "Irrigation",
    client: "Somali Regional State Bureau of Agriculture",
    location: "Jigjiga Zone, Somali Region",
    projectSize: "1,500 HA",
    completionDate: "2022",
    status: "Completed",
    isFeatured: true,
    image: "/hagec-website-images/photo_5947369626163416449_y.jpeg",
    shortDescription: "Feasibility study, detailed design, and construction supervision of a 1,500 HA surface irrigation scheme fed by Fafen River in the Jigjiga Zone.",
  },
  {
    id: 2,
    title: "Wabe Shebelle Solar-Pump System",
    slug: "wabe-shebelle-solar-pump",
    category: "Solar-Pump",
    client: "FAO Ethiopia",
    location: "Gode Zone, Somali Region",
    projectSize: "—",
    completionDate: "2021",
    status: "Completed",
    isFeatured: true,
    image: "/hagec-website-images/photo_5947369626163416453_y.jpeg",
    shortDescription: "Design and installation supervision of a 45 kW solar-pump system providing irrigation water to 200 smallholder farmers.",
  },
  {
    id: 3,
    title: "Waberi Canal Rehabilitation",
    slug: "waberi-canal-rehabilitation",
    category: "Irrigation",
    client: "World Bank / Somali Regional State",
    location: "Gode Zone, Somali Region",
    projectSize: "800 HA",
    completionDate: "2023",
    status: "Completed",
    isFeatured: false,
    image: "/hagec-website-images/photo_5947369626163416455_y.jpeg",
    shortDescription: "Rehabilitation of primary and secondary canals of the existing 800 HA Waberi irrigation scheme, including hydraulic modelling and design.",
  },
  {
    id: 4,
    title: "Jigjiga Water Supply EIA",
    slug: "jigjiga-water-supply-eia",
    category: "EIA",
    client: "Somali Urban Water Supply Authority",
    location: "Jigjiga, Somali Region",
    projectSize: "—",
    completionDate: "2023",
    status: "Completed",
    isFeatured: false,
    image: "/hagec-website-images/photo_5947369626163416456_y.jpeg",
    shortDescription: "Full Environmental Impact Assessment and Environmental and Social Management Plan for the Jigjiga municipal water supply expansion project.",
  },
  {
    id: 5,
    title: "Somali Region Land Use Mapping",
    slug: "somali-region-land-use-mapping",
    category: "GIS & Surveying",
    client: "UNDP Ethiopia",
    location: "Somali Region (Multi-zone)",
    projectSize: "—",
    completionDate: "2022",
    status: "Completed",
    isFeatured: false,
    image: "/hagec-website-images/photo_5947369626163416459_y.jpeg",
    shortDescription: "Satellite image-based land use and land cover mapping of five zones of the Somali Region using GIS and remote sensing analysis.",
  },
  {
    id: 6,
    title: "Erer Valley Geotechnical Study",
    slug: "erer-valley-geotechnical",
    category: "Geotechnical",
    client: "Ministry of Water & Energy, Ethiopia",
    location: "Erer Valley, Somali Region",
    projectSize: "—",
    completionDate: "2021",
    status: "Completed",
    isFeatured: false,
    image: "/hagec-website-images/photo_5947369626163416462_y.jpeg",
    shortDescription: "Geotechnical investigation for a proposed earth dam, including borehole drilling, laboratory testing, and foundation engineering report.",
  },
  {
    id: 7,
    title: "Fafen Basin Hydrological Study",
    slug: "fafen-basin-hydrology",
    category: "Hydrology",
    client: "FAO Ethiopia / Somali Regional State",
    location: "Fafen River Basin, Somali Region",
    projectSize: "—",
    completionDate: "2024",
    status: "Ongoing",
    isFeatured: true,
    image: "/hagec-website-images/photo_5947369626163416465_y.jpeg",
    shortDescription: "Comprehensive hydrological and water resources study of the Fafen River Basin including flood analysis, water balance, and flow rating curves.",
  },
  {
    id: 8,
    title: "Northern Somali Irrigation Feasibility",
    slug: "northern-somali-irrigation-feasibility",
    category: "Feasibility Study",
    client: "African Development Bank",
    location: "Shinile Zone, Somali Region",
    projectSize: "2,500 HA",
    completionDate: "2025",
    status: "Ongoing",
    isFeatured: false,
    image: "/hagec-website-images/photo_5947369626163416467_y.jpeg",
    shortDescription: "Pre-feasibility and feasibility study for a new 2,500 HA irrigation scheme in Shinile Zone, including topographic survey and hydrological assessment.",
  },
];